version: '3.6'

services:
  db:
    image: postgres
    container_name: link_tracker_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: link_tracker
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  zookeeper:
    networks:
      - kafka_network
    extends:
      file: docker/zookeeper/docker-compose.zookeeper.yml
      service: zookeeper

  broker1:
    networks:
      - kafka_network
    extends:
      file: docker/kafka/docker-compose.kafka.yml
      service: broker1
    depends_on:
      zookeeper:
        condition: service_healthy

  schemaregistry:
    networks:
      - kafka_network
    extends:
      file: docker/schemaregistry/docker-compose.schemaregistry.yml
      service: schemaregistry
    depends_on:
      zookeeper:
        condition: service_healthy

  control-center:
    networks:
      - kafka_network
    extends:
      file: docker/control-center/docker-compose.control-center.yml
      service: control-center
    depends_on:
      broker1:
        condition: service_healthy
      schemaregistry:
        condition: service_healthy


networks:
  kafka_network:
    name: kafka_docker_net
